# Generated by Django 5.1.6 on 2025-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloRSF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarcaRSF', models.CharField(max_length=50, null=True)),
                ('Articulo', models.CharField(max_length=50, null=True)),
                ('Fabrica', models.CharField(max_length=50, null=True)),
                ('Descripcion', models.TextField(null=True)),
                ('TipoTxt', models.CharField(max_length=50, null=True)),
                ('MarcaOriginal', models.CharField(max_length=50, null=True)),
                ('PrecioLista', models.CharField(max_length=50, null=True)),
                ('PrecioNeto', models.CharField(max_length=50, null=True)),
                ('StockFinal', models.IntegerField(null=True)),
                ('ModuloVenta', models.IntegerField(null=True)),
                ('Rubro', models.CharField(max_length=50, null=True)),
                ('Segmento', models.CharField(max_length=50, null=True)),
                ('Enlace', models.CharField(max_length=50, null=True)),
                ('OEM', models.CharField(max_length=100, null=True)),
                ('CodigoBarra', models.CharField(max_length=50, null=True)),
                ('CodigoRSF', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
